// <auto-generated />
namespace MyFirstABP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AbpZero_Installed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AbpZero_Installed));
        
        string IMigrationMetadata.Id
        {
            get { return "201711291353512_AbpZero_Installed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
